name: Auto Merge Community Scripts

on:
  pull_request:
    branches: [master]
    paths:
      - 'Community Scripts/**'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: Enable Pull Request Automerge
      run: gh pr merge --merge --auto "1"
      env:
        GH_TOKEN: ${{ secrets.PAT }}