name: Auto Merge Community Scripts

on:
  pull_request:
    branches: [master]
    paths:
      - 'Community Scripts/**'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Enable Pull Request Automerge
        run: |
          gh pr merge --merge --auto "1"
          gh pr review --approve "1"
        env:
          GH_TOKEN: ${{ secrets.PAT }}