name: Auto Merge Community Scripts

on:
  pull_request:
    branches: [master]
    paths:
      - 'Community Scripts/**'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Enable Pull Request Automerge
        run: |
          gh pr merge --merge --auto "$PR_URL"
          gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{ secrets.PAT }}